name: 'CI'

on:
  push:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Wipe workspace'
        run: find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          context: docker
          tags: qflipper-build:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build application in docker
        run: docker run --rm --privileged -v $(pwd):/project qflipper-build:latest /project/build_linux.sh

      - name: Publish application
        uses: actions/upload-artifact@v4
        with:
          name: qFlipper-x86_64.AppImage
          path: |
                ./build/qFlipper-x86_64.AppImage
          if-no-files-found: error
